# Wikimedia

services:

  consumer-db:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    container_name: wm-consumer-db
    networks:
      - wikimedia-nw
    restart: always
    volumes:
      - /mySql/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wikimedia

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - 22181:2181
    networks:
      - wikimedia-nw
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - wikimedia-nw
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://kafka:29091
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092, PLAINTEXT_HOST://localhost:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build:
      context: .
      dockerfile: ./wikimedia-producer/Dockerfile
    container_name: wm-producer
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - wikimedia-nw
    environment:
      - "KAFKA_HOST=kafka"

  consumer:
    build:
      context: .
      dockerfile: ./wikimedia-consumer/Dockerfile
    container_name: wm-consumer
    depends_on:
      - kafka
      - consumer-db
    restart: unless-stopped
    networks:
      - wikimedia-nw
    environment:
      - "KAFKA_HOST=kafka"
      - "DATASOURCE_HOST=consumer-db"

networks:
  wikimedia-nw:

