### Producer

spring:

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer